### PR TITLE
add a prefix uuid value and examples

### PR DESCRIPTION
**Pull request by time4tea**

### CODE REVIEW

**Comment by time4tea** [comment]
Will see if this can be applied more generically to valuefactories

**Comment by daviddenton** [comment]
Is this still WIP @time4tea ?

**Comment by time4tea** [comment]
Got some feedback that it was a bit too specific for a library. Suggest close and add as an example.

**Comment by daviddenton** [comment]
Closing as possibly would be better as an example of how to extend the library. :)

**Pull request closed without merging**
